// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEP0YHExrHgx3iFJgwjjsuO0KltHyp5DI',
    appId: '1:116246487522:web:f50365a2a5b86ef262d9bb',
    messagingSenderId: '116246487522',
    projectId: 'my-clone-instragram',
    authDomain: 'my-clone-instragram.firebaseapp.com',
    storageBucket: 'my-clone-instragram.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_8mlWzX6syDdpdt8LCznbHO2w9IlMhlI',
    appId: '1:116246487522:android:7aa0f8e8fa49e69b62d9bb',
    messagingSenderId: '116246487522',
    projectId: 'my-clone-instragram',
    storageBucket: 'my-clone-instragram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5zuNlKo8iat_Gtu2gvVTM986EfqH64MQ',
    appId: '1:116246487522:ios:f96d6b34f18280a662d9bb',
    messagingSenderId: '116246487522',
    projectId: 'my-clone-instragram',
    storageBucket: 'my-clone-instragram.appspot.com',
    iosClientId: '116246487522-v73k5onecscu6jopmuaa1u6043rfs8e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5zuNlKo8iat_Gtu2gvVTM986EfqH64MQ',
    appId: '1:116246487522:ios:f96d6b34f18280a662d9bb',
    messagingSenderId: '116246487522',
    projectId: 'my-clone-instragram',
    storageBucket: 'my-clone-instragram.appspot.com',
    iosClientId: '116246487522-v73k5onecscu6jopmuaa1u6043rfs8e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneApp',
  );
}
